spring.application.name=cugDirectory

spring.datasource.url=jdbc:mysql://localhost:3306/cug_directory
spring.datasource.username=root
spring.datasource.password=Force@#753

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
